import { z } from "zod";

import type { MetricDefinition, MetricValueKind, SourceKey } from "../contracts";

export const metricImplementationStatusSchema = z.enum([
  "CERTIFIABLE",
  "DATA_PENDING",
  "BUSINESS_RULE_REQUIRED",
  "SOURCE_LIMITED",
  "NOT_V1",
]);

export type MetricImplementationStatus = z.infer<typeof metricImplementationStatusSchema>;

export const dashboardSectionSchema = z.enum([
  "Executive Health",
  "Revenue Intelligence",
  "Customer Intelligence",
  "Product Intelligence",
  "Operations Intelligence",
  "Marketing Intelligence",
  "Growth Intelligence",
  "Financial Intelligence",
  "Insights and Data Quality",
]);

export type DashboardSection = z.infer<typeof dashboardSectionSchema>;

export interface MetricCatalogEntry {
  readonly key: string;
  readonly label: string;
  readonly sections: readonly DashboardSection[];
  readonly v1Class: "core" | "future_ready_core" | "conditional" | "not_v1";
  readonly valueKind: MetricValueKind;
  readonly sourceKeys: readonly SourceKey[];
  readonly sources: string;
  readonly sourceFields: string;
  readonly calculation: string;
  readonly status: MetricImplementationStatus;
  readonly blockingReason: string | null;
}

const entry = (value: MetricCatalogEntry): MetricCatalogEntry => Object.freeze(value);

export const metricCatalog = Object.freeze([
  entry({
    key: "commerce.net_sales",
    label: "Net sales",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "net_sales",
    calculation:
      "Pass through Shopify canonical net_sales under the approved DEC-015 revenue policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.orders",
    label: "Orders",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "orders",
    calculation: "Pass through Shopify aggregate orders under the approved DEC-015 order policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.average_order_value",
    label: "Average order value",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "average_order_value",
    calculation:
      "Pass through ShopifyQL average_order_value verbatim; never locally re-divided (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.returning_rate",
    label: "Returning customer rate",
    sections: ["Executive Health", "Customer Intelligence"],
    v1Class: "core",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "returning_customer_rate",
    calculation:
      "Pass through Shopify aggregate customer classification rate; disclose blank classification rows.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.sales_trend",
    label: "Sales trend",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales timeseries",
    sourceFields: "period, net_sales",
    calculation: "Provider-period net-sales points under the approved DEC-015 revenue basis.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.native_channel_mix",
    label: "Native channel mix",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "ShopifyQL native channels and Mappings",
    sourceFields: "sales_channel, net_sales, Mappings",
    calculation:
      "ShopifyQL sales_channel values verbatim under DEC-016; blank or unmatched values remain Unclassified.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "operations.fulfillment_summary",
    label: "Fulfillment summary",
    sections: ["Executive Health", "Operations Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify fulfillment analytics",
    sourceFields: "orders_fulfilled, orders_shipped, orders_delivered",
    calculation:
      "Pass through provider orders_fulfilled/orders_shipped/orders_delivered aggregates with event-dated semantics (DEC-016).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "plan.revenue_variance",
    label: "Revenue versus plan",
    sections: ["Executive Health", "Revenue Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify actuals and Corrected Budget/Forecast plan",
    sourceFields: "approved actual revenue, overlapping plan period",
    calculation: "Actual minus clearly labelled Plan for the same approved period and scope.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason:
      "Actual revenue policy, plan mapping, and comparison behavior remain unapproved.",
  }),
  entry({
    key: "executive.business_health_score",
    label: "Business Health score",
    sections: ["Executive Health"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Multiple approved metrics",
    sourceFields: "approved signals, weights, normalization, thresholds",
    calculation: "Weighted score only after every input and threshold is approved.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Signals, weights, normalization, and thresholds are not approved.",
  }),
  entry({
    key: "executive.recommendations",
    label: "Executive recommendations",
    sections: ["Executive Health", "Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Approved deterministic alerts",
    sourceFields: "active approved alert outputs",
    calculation:
      "Rank only through an approved deterministic ranking policy; never generate AI narrative.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Alert thresholds and ranking policy are not approved.",
  }),
  entry({
    key: "commerce.gross_sales",
    label: "Gross sales",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "gross_sales",
    calculation:
      "Pass through Shopify canonical gross_sales under the approved DEC-015 revenue policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.discounts",
    label: "Discounts",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "discounts",
    calculation:
      "Pass through provider discounts value and sign; never subtracted twice (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.returns",
    label: "Returns",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "returns",
    calculation:
      "Pass through provider returns recognized on the Shopify reporting event date (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.shipping_charges",
    label: "Shipping charges",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "shipping_charges",
    calculation: "Pass through provider shipping charges displayed separately (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.taxes",
    label: "Taxes",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "taxes",
    calculation: "Pass through provider taxes displayed separately (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.total_sales",
    label: "Total sales",
    sections: ["Revenue Intelligence", "Financial Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "total_sales",
    calculation: "Pass through Shopify canonical total_sales under the approved DEC-015 policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.sales",
    label: "Product/SKU sales",
    sections: ["Revenue Intelligence", "Product Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product/variant dimensions",
    sourceFields: "line_type, product_title, product_variant_title, product_variant_sku, net_sales",
    calculation:
      "Merchandise net sales grouped by product/variant/SKU; non-merchandise rows excluded (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.units_sold",
    label: "Units sold",
    sections: ["Revenue Intelligence", "Product Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product line classification",
    sourceFields: "line_type, product_variant_sku, net_items_sold",
    calculation: "Sum net_items_sold for explicitly merchandise-classified rows only.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.purchase_heatmap",
    label: "Purchase heatmap",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL purchase time",
    sourceFields: "day_of_week, hour_of_day, orders",
    calculation: "Qualifying orders grouped by New York day-of-week and hour under DEC-015.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.detailed_order_drilldown",
    label: "Detailed twelve-month order drill-down",
    sections: ["Revenue Intelligence", "Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify Admin GraphQL orders",
    sourceFields: "order and line-item history",
    calculation: "Return sanitized detailed records only when the requested range is complete.",
    status: "SOURCE_LIMITED",
    blockingReason:
      "The order-level drill-down dataset has not been implemented. The read_all_orders scope it depends on is granted, so this is an implementation gap, not a source limit.",
  }),
  entry({
    key: "commerce.predictive_forecast",
    label: "Month-end predictive forecast",
    sections: ["Revenue Intelligence"],
    v1Class: "not_v1",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "Future model",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "Predictive forecasting is explicitly outside V1.",
  }),
  entry({
    key: "customers.new_count",
    label: "New customers",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL customer classification",
    sourceFields: "new_or_returning_customer, customers",
    calculation: "Sum Shopify rows classified as new; expose unclassified rows separately.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.returning_count",
    label: "Returning customers",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL customer classification",
    sourceFields: "new_or_returning_customer, customers",
    calculation: "Sum Shopify rows classified as returning; expose unclassified rows separately.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.billing_geography",
    label: "Customer billing geography",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL billing geography",
    sourceFields: "billing_country, billing_region, orders",
    calculation: "PII-free billing country/region aggregates for qualifying orders under DEC-015.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.web_funnel",
    label: "Shopify acquisition funnel",
    sections: ["Customer Intelligence", "Marketing Intelligence"],
    v1Class: "core",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sessions",
    sourceFields:
      "sessions, online_store_visitors, sessions_with_cart_additions, sessions_that_reached_checkout, sessions_that_completed_checkout, conversion_rate",
    calculation:
      "Expose Shopify provider funnel counts and conversion rate for the requested period.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.active",
    label: "Active customers",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Detailed or approved aggregate customer history",
    sourceFields: "customer/order history",
    calculation: "Apply an approved activity window to complete customer history.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Activity definition and complete detailed history are absent.",
  }),
  entry({
    key: "customers.cohorts",
    label: "Customer cohorts",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "Detailed customer/order history",
    sourceFields: "customer identity, first order, subsequent orders",
    calculation: "Cohort retention over complete history.",
    status: "SOURCE_LIMITED",
    blockingReason:
      "Cohort retention has not been implemented. The read_all_orders scope needed for complete order history is granted, so this is an implementation gap, not a source limit.",
  }),
  entry({
    key: "customers.realized_ltv",
    label: "Realized LTV",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Detailed orders and optional approved costs",
    sourceFields: "customer identity, complete orders, optional costs",
    calculation: "Approved revenue- or contribution-based lifetime value.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "LTV basis, identity policy, and complete history are unresolved.",
  }),
  entry({
    key: "customers.rfm",
    label: "RFM segmentation",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Detailed customer/order history",
    sourceFields: "recency, frequency, monetary history",
    calculation: "Apply approved RFM bands to complete history.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "RFM bands and complete history are unresolved.",
  }),
  entry({
    key: "customers.predictive_churn",
    label: "Predictive churn",
    sections: ["Customer Intelligence"],
    v1Class: "not_v1",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "Future model",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "Predictive churn is explicitly outside V1.",
  }),
  entry({
    key: "products.mix",
    label: "Product mix",
    sections: ["Product Intelligence"],
    v1Class: "core",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product/variant dimensions",
    sourceFields: "net_sales or net_items_sold",
    calculation:
      "Merchandise net-sales share of the merchandise net-sales total, in basis points (DEC-016 net-sales basis).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.catalog",
    label: "Product price and status",
    sections: ["Product Intelligence"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Shopify Admin GraphQL",
    sourceFields: "Product.id/title/status; Variant.id/SKU/price",
    calculation: "Return current sanitized catalog fields without deriving history.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.units_velocity",
    label: "Units-sold velocity trend",
    sections: ["Product Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product line timeseries",
    sourceFields: "period, line_type, SKU, net_items_sold",
    calculation: "Group merchandise net_items_sold by approved provider period; descriptive only.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "inventory.shopify_current",
    label: "Current Shopify inventory",
    sections: ["Product Intelligence", "Operations Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify Admin GraphQL InventoryLevel",
    sourceFields: "location, quantities available/on_hand/incoming/committed",
    calculation: "Return provider quantities for represented Shopify locations only.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "quality.missing_sku_cost",
    label: "Missing SKU cost",
    sections: ["Product Intelligence", "Insights and Data Quality"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify catalog and approved SKU_Costs",
    sourceFields: "active/sold SKU, InventoryItem.unitCost, effective SKU_Costs",
    calculation:
      "List active/sold SKUs lacking an applicable approved cost; never substitute Budget/PO cost.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "inventory.sell_through",
    label: "Sell-through",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Inventory history/S&OP",
    sourceFields: "opening, receipts, units sold, ending inventory",
    calculation: "Use only an approved sell-through definition and clean historical catalog.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Sell-through formula and complete history are unresolved.",
  }),
  entry({
    key: "inventory.value",
    label: "Inventory value",
    sections: ["Product Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Inventory and effective SKU_Costs",
    sourceFields: "quantity, canonical-unit mapping, approved effective cost",
    calculation: "Quantity multiplied by approved effective canonical-unit cost.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason:
      "Cost authority, effective cost, and pack/unit mapping conflict are unresolved.",
  }),
  entry({
    key: "inventory.runway_reorder",
    label: "Inventory Runway & Reorder Alert",
    sections: ["Product Intelligence", "Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "date",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify units plus Inventory/Forecast/Production/Rules_Targets",
    sourceFields: "complete inventory, velocity, incoming units, lead time, safety buffer",
    calculation: "Calculate days-on-hand, stockout, and reorder only from approved rules.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason:
      "Velocity period, lead time, safety buffer, thresholds, and complete inventory are absent.",
  }),
  entry({
    key: "products.frequently_bought_together",
    label: "Frequently bought together",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "Detailed order line history",
    sourceFields: "complete order-product pairs",
    calculation: "Calculate product-pair support/confidence under approved thresholds.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Detailed history and pair thresholds are unresolved.",
  }),
  entry({
    key: "operations.shipped_delivered",
    label: "Shipped and delivered counts",
    sections: ["Operations Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify fulfillment analytics",
    sourceFields: "orders_shipped, orders_delivered",
    calculation: "Return provider aggregates with an explicit partial-coverage warning.",
    status: "SOURCE_LIMITED",
    blockingReason: "Carrier event coverage is not complete enough for a complete-company claim.",
  }),
  entry({
    key: "inventory.combined",
    label: "Combined SNAPL/YBYD inventory",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "manual_workbook"],
    sources: "Shopify plus PRODUCTION Inventory",
    sourceFields: "dated warehouse/SKU quantities and mappings",
    calculation: "Combine only complete mapped location snapshots without double-counting overlap.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION inventory/mapping rows are empty.",
  }),
  entry({
    key: "inventory.lots",
    label: "Lot and best-by visibility",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Inventory_Lots and S&OP reference",
    sourceFields: "warehouse, SKU, lot, best-by, quantity, status",
    calculation:
      "Return validated current lot rows and quantities; no movement history is inferred.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION lot records are empty.",
  }),
  entry({
    key: "inventory.fefo",
    label: "FEFO visibility",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["google_sheets"],
    sources: "Inventory_Lots and Depletions",
    sourceFields: "lot best-by, availability, lot-linked depletion",
    calculation:
      "Evaluate only under an approved FEFO rule and sufficiently linked depletion records.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "FEFO rule and complete lot-linked depletion data are absent.",
  }),
  entry({
    key: "forecast.variance",
    label: "Forecast versus actual",
    sections: ["Operations Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "PRODUCTION Forecast plus Shopify actuals",
    sourceFields: "single valid Active forecast version, period/SKU/channel actual units",
    calculation: "Actual units minus forecast units for identical period/SKU/channel scope.",
    status: "DATA_PENDING",
    blockingReason:
      "PRODUCTION forecast and required mappings are empty; actual policy may further limit revenue variance.",
  }),
  entry({
    key: "production.incoming",
    label: "Incoming production",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Production and S&OP reference",
    sourceFields: "PO line, SKU, units, arrival, status, destination",
    calculation:
      "Return validated PO-line exposure and received quantities without inventing schedule events.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION production rows are empty.",
  }),
  entry({
    key: "production.timeline",
    label: "Production timeline",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "PRODUCTION Production and S&OP reference",
    sourceFields: "order/production/arrival dates and status",
    calculation: "Return validated current PO milestones; no event history is inferred.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION rows are empty and the S&OP schedule remains unreliable.",
  }),
  entry({
    key: "production.cost_payment",
    label: "Production cost and payment exposure",
    sections: ["Operations Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "PRODUCTION Production; Budget/S&OP plan references",
    sourceFields: "PO unit/freight/deposit/balance values and dates",
    calculation: "Sum validated PO exposure separately from actual expenses and realized COGS.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION PO values are empty; reference-source cost conflicts remain.",
  }),
  entry({
    key: "inventory.depletions",
    label: "Additional depletions",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Depletions",
    sourceFields: "date, warehouse, SKU, quantity, reason",
    calculation: "Sum validated non-revenue depletion events by requested dimensions.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION depletion records are empty.",
  }),
  entry({
    key: "klaviyo.email_overview",
    label: "Email performance overview",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields:
      "recipients, delivered/rate, opens_unique/rate, clicks_unique/rate, click_to_open_rate, bounced/rate, unsubscribe_uniques/rate, spam complaints/rate",
    calculation: "Expose verified Reporting API statistics with send-date semantics.",
    status: "DATA_PENDING",
    blockingReason:
      "The audited account has no report/event activity and live credentials are deferred.",
  }),
  entry({
    key: "klaviyo.email_recipients",
    label: "Email recipients",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "recipients",
    calculation: "Pass through the report recipient count using send-date semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_delivery_rate",
    label: "Email delivery rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "delivery_rate",
    calculation: "Pass through the verified report delivery rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_open_rate",
    label: "Email open rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "open_rate",
    calculation: "Pass through the verified report open rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_click_rate",
    label: "Email click rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "click_rate",
    calculation: "Pass through the verified report click rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_click_to_open_rate",
    label: "Email click-to-open rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "click_to_open_rate",
    calculation: "Pass through the verified report click-to-open rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_bounce_rate",
    label: "Email bounce rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "bounce_rate",
    calculation: "Pass through the verified report bounce rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_unsubscribe_rate",
    label: "Email unsubscribe rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "unsubscribe_rate",
    calculation: "Pass through the verified report unsubscribe rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_spam_complaints",
    label: "Email spam complaints",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "spam_complaints",
    calculation: "Pass through the verified report complaint count.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.sms_overview",
    label: "SMS performance overview",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo reports and selected metrics",
    sourceFields: "sent, received/delivered, clicked, failed, unsubscribed",
    calculation: "Expose supported verified SMS report/aggregate values with their time semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity and live credentials are deferred.",
  }),
  entry({
    key: "klaviyo.sms_sent",
    label: "SMS sent",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Sent Text Message / report recipients",
    calculation: "Expose the verified source count with its report/event-time label.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_delivered",
    label: "SMS delivered or received",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Received Text Message / supported delivery statistic",
    calculation:
      "Expose only the exact supported delivered/received measure and label it accordingly.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_clicked",
    label: "SMS clicked",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Clicked Text Message",
    calculation: "Expose the verified click count with its time semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_failed",
    label: "SMS failed",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Failed to Deliver Text Message",
    calculation: "Expose the verified failed-delivery count.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_unsubscribed",
    label: "SMS unsubscribed",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Unsubscribed from Text Messaging Marketing",
    calculation: "Expose the verified SMS unsubscribe count.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.campaign_performance",
    label: "Campaign performance",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "status",
    sourceKeys: ["klaviyo"],
    sources: "campaign-values-reports",
    sourceFields: "campaign/message/channel groupings and verified report statistics",
    calculation:
      "Map each report row to a sanitized table; report values retain send-date semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no campaigns/report rows.",
  }),
  entry({
    key: "klaviyo.flow_performance",
    label: "Flow performance",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "status",
    sourceKeys: ["klaviyo"],
    sources: "flow-values-reports",
    sourceFields: "flow/message/channel groupings and verified report statistics",
    calculation:
      "Map each report row to a sanitized table; report values retain send-date semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited flows currently have no report rows.",
  }),
  entry({
    key: "klaviyo.attributed_revenue",
    label: "Klaviyo-attributed revenue",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "money",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo report conversion value",
    sourceFields: "conversion_value for verified Placed Order metric",
    calculation: "Expose only as Klaviyo-attributed revenue under Klaviyo attribution semantics.",
    status: "DATA_PENDING",
    blockingReason:
      "No report data exists; attribution settings must be recorded before production readiness.",
  }),
  entry({
    key: "klaviyo.engagement_trend",
    label: "Klaviyo engagement trend",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo metric-aggregates",
    sourceFields: "dates and count/unique/sum_value measurements",
    calculation: "Return event-time trend points normalized to America/New_York display periods.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no events and live credentials are deferred.",
  }),
  entry({
    key: "marketing.spend",
    label: "Marketing spend",
    sections: ["Marketing Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Marketing_Spend",
    sourceFields: "date, platform, campaign, spend USD",
    calculation:
      "Sum validated spend rows by requested period/dimensions; do not infer attribution.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION marketing-spend rows are empty.",
  }),
  entry({
    key: "marketing.cac",
    label: "Customer acquisition cost",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Approved spend and acquisition attribution",
    sourceFields: "approved spend numerator and acquired-customer denominator",
    calculation:
      "Numerator divided by denominator only under an approved blended/attributed policy.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Numerator, denominator, and acquisition attribution are not approved.",
  }),
  entry({
    key: "marketing.roas",
    label: "ROAS",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo", "google_sheets"],
    sources: "Approved attributed revenue and spend",
    sourceFields: "approved attributed-revenue numerator and spend denominator",
    calculation:
      "Attributed revenue divided by matching spend only under an approved attribution policy.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Revenue attribution and spend scope are not approved.",
  }),
  entry({
    key: "marketing.ltv_cac",
    label: "LTV:CAC",
    sections: ["Marketing Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Approved LTV and CAC",
    sourceFields: "approved LTV numerator and CAC denominator",
    calculation: "Approved LTV divided by approved CAC for an identical scope.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Both LTV and CAC policies are unresolved.",
  }),
  entry({
    key: "social.performance",
    label: "Social growth and engagement",
    sections: ["Marketing Intelligence", "Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Social_Metrics",
    sourceFields: "dated platform/account followers and optional engagement measures",
    calculation:
      "Return validated dated observations; missing optional measures remain unavailable.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION social records are empty.",
  }),
  entry({
    key: "marketing.content_conversion",
    label: "Content conversion",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "klaviyo"],
    sources: "GA4/ad/content tracking",
    sourceFields: "content identifiers and verified attribution",
    calculation: "No V1 calculation without verified tracking and attribution.",
    status: "SOURCE_LIMITED",
    blockingReason: "GA4/ad access and content tagging are not available.",
  }),
  entry({
    key: "sources.freshness",
    label: "Source freshness",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["shopify", "klaviyo", "google_drive", "google_sheets"],
    sources: "All source-status contracts",
    sourceFields: "checkedAt, lastSuccessfulAt, dataAsOf, source state",
    calculation:
      "Expose verifiable source timestamps/states without equating file modification with business freshness.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "sources.historical_completeness",
    label: "Historical completeness",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Shopify history contract",
    sourceFields: "mode, requested range, earliest detailed record, completeness",
    calculation: "Expose aggregate-versus-detailed history and complete-for-request status.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "quality.unclassified_channel",
    label: "Unclassified channel",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify channel values and Mappings",
    sourceFields: "source channel plus effective mapping",
    calculation:
      "Count qualifying orders whose sales channel is Unclassified under the DEC-016 channel policy; never guessed.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "quality.klaviyo_no_activity",
    label: "Klaviyo no-data state",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo source status",
    sourceFields: "connection, event/report presence",
    calculation:
      "Return No activity when valid configured reads contain no genuine events/reports.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "quality.sop_validation",
    label: "S&OP validation",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["google_drive"],
    sources: "Approved S&OP XLSX",
    sourceFields: "worksheet names, non-empty/formula/error/placeholder counts",
    calculation:
      "Expose detected formula errors/placeholders without repairing or treating them as actuals.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "alerts.low_inventory",
    label: "Low inventory alert",
    sections: ["Insights and Data Quality", "Product Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Inventory and Rules_Targets",
    sourceFields: "available quantity and approved threshold",
    calculation: "Compare inventory to an effective approved threshold only.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "No approved low-inventory threshold exists.",
  }),
  entry({
    key: "alerts.conversion_decline",
    label: "Conversion decline alert",
    sections: ["Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify funnel and Rules_Targets",
    sourceFields: "comparable conversion periods and approved threshold",
    calculation: "Evaluate equivalent periods only under an approved threshold/comparison rule.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Comparison and threshold policy is absent.",
  }),
  entry({
    key: "alerts.refund_increase",
    label: "Refund increase alert",
    sections: ["Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify returns/refunds and Rules_Targets",
    sourceFields: "approved refund metric/comparison and threshold",
    calculation: "Evaluate only after refund policy and threshold approval.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Refund definition, comparison, and threshold are absent.",
  }),
  entry({
    key: "alerts.fulfillment_backlog",
    label: "Fulfillment backlog alert",
    sections: ["Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify orders/fulfillments and Rules_Targets",
    sourceFields: "approved unfulfilled status, age, threshold",
    calculation: "Evaluate only under approved backlog age/status thresholds.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Backlog status, age, and threshold policy is absent.",
  }),
  entry({
    key: "actions.assign",
    label: "Assign action",
    sections: ["Insights and Data Quality"],
    v1Class: "not_v1",
    valueKind: "status",
    sourceKeys: ["google_sheets"],
    sources: "Write workflow",
    sourceFields: "not applicable",
    calculation: "Not implemented in read-only V1.",
    status: "NOT_V1",
    blockingReason: "Would require an unauthorized write workflow.",
  }),
  entry({
    key: "recommendations.ai",
    label: "AI-generated recommendations",
    sections: ["Insights and Data Quality"],
    v1Class: "not_v1",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Future AI system",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "AI-generated recommendations are explicitly outside V1.",
  }),
  entry({
    key: "partners.performance",
    label: "Partner performance",
    sections: ["Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Partner_Performance",
    sourceFields: "period, type, partner, platform, optional orders/revenue/commission",
    calculation:
      "Aggregate only supplied attributed partner values; missing measures remain unavailable.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION partner-performance rows are empty.",
  }),
  entry({
    key: "growth.open_pipeline",
    label: "Open pipeline",
    sections: ["Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Growth_Pipeline",
    sourceFields: "pipeline type, opportunity, status, optional value",
    calculation: "Count Open opportunities and separately sum only supplied values.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION growth-pipeline rows are empty.",
  }),
  entry({
    key: "growth.pipeline_by_type",
    label: "Pipeline by category",
    sections: ["Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Growth_Pipeline",
    sourceFields: "pipeline type, status, optional value",
    calculation: "Group validated current opportunities by pipeline type and status.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION growth-pipeline rows are empty.",
  }),
  entry({
    key: "growth.next_actions",
    label: "Pipeline next actions",
    sections: ["Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "date",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Growth_Pipeline",
    sourceFields: "opportunity, next action, due date, value",
    calculation:
      "Return supplied current next actions ordered by due date; do not rank by invented probability.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION growth-pipeline rows are empty.",
  }),
  entry({
    key: "growth.weighted_pipeline",
    label: "Weighted pipeline",
    sections: ["Growth Intelligence"],
    v1Class: "not_v1",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Future approved probability source",
    sourceFields: "value and approved probability",
    calculation: "Not calculated from the simplified V1 source contract.",
    status: "NOT_V1",
    blockingReason:
      "The approved simplified Growth_Pipeline has no probability field; predictive probability is outside V1.",
  }),
  entry({
    key: "finance.actual_expenses",
    label: "Actual operating expenses",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Finance_Actuals",
    sourceFields: "date, category, amount USD",
    calculation: "Sum validated actual-expense rows, including explicit negative correction rows.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION finance-actual rows are empty.",
  }),
  entry({
    key: "finance.expense_composition",
    label: "Expense composition",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Finance_Actuals",
    sourceFields: "category, amount USD",
    calculation: "Group validated actual expenses by approved category.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION finance-actual rows are empty.",
  }),
  entry({
    key: "finance.cash_position",
    label: "Cash position",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["manual_workbook"],
    sources: "PRODUCTION Cash",
    sourceFields: "latest dated account balance and restricted cash",
    calculation:
      "Return latest validated account balances; unrestricted totals require complete account coverage.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION cash rows are empty and completeness is not established.",
  }),
  entry({
    key: "finance.budget_vs_actual",
    label: "Budget versus actual",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "Corrected Budget plan and PRODUCTION actuals",
    sourceFields: "mapped plan and actual categories/periods",
    calculation:
      "Actual minus Plan for identical approved categories and periods, with labels preserved.",
    status: "DATA_PENDING",
    blockingReason: "Actual rows and approved plan/actual category mappings are absent.",
  }),
  entry({
    key: "finance.actual_margin",
    label: "Actual margin",
    sections: ["Financial Intelligence", "Product Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets", "google_drive"],
    sources: "Approved sales and effective SKU costs",
    sourceFields: "approved net sales, units, effective costs, mappings",
    calculation:
      "Approved revenue minus approved realized cost without overlapping-cost double counting.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Sales policy and SKU cost-authority conflict remain unresolved.",
  }),
  entry({
    key: "finance.monthly_burn",
    label: "Monthly burn",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "PRODUCTION Finance_Actuals",
    sourceFields: "approved cash/accrual expense scope",
    calculation: "Calculate only from an approved burn definition and complete expense scope.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Burn scope and cash-versus-accrual policy are not approved.",
  }),
  entry({
    key: "finance.cash_runway",
    label: "Cash runway",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "duration_seconds",
    sourceKeys: ["google_sheets"],
    sources: "PRODUCTION Cash and approved burn",
    sourceFields: "approved available cash and burn",
    calculation: "Available cash divided by approved burn under an approved runway policy.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Available-cash and burn/runway definitions are not approved.",
  }),
  entry({
    key: "finance.fairafric_rebate",
    label: "Fairafric rebate",
    sections: ["Financial Intelligence", "Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "Production rows and Rules_Targets",
    sourceFields: "qualifying units/PO plus approved rebate parameters",
    calculation: "Apply only a signed/effective approved rebate rule.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "No approved rebate rule registry exists.",
  }),
  entry({
    key: "finance.predictive_cashflow",
    label: "Predictive cash flow",
    sections: ["Financial Intelligence"],
    v1Class: "not_v1",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Future model",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "Predictive cash-flow modelling is explicitly outside V1.",
  }),
] satisfies readonly MetricCatalogEntry[]);

export function metricCatalogEntry(key: string): MetricCatalogEntry | undefined {
  return metricCatalog.find((definition) => definition.key === key);
}

export const activeMetricDefinitions: readonly MetricDefinition[] = metricCatalog
  .filter((definition) => definition.v1Class !== "not_v1")
  .map((definition) => ({
    key: definition.key,
    schemaVersion: "1.0" as const,
    definitionVersion: "1.0",
    classification: definition.v1Class as "core" | "future_ready_core" | "conditional",
    valueKind: definition.valueKind,
    sourceKeys: [...definition.sourceKeys],
    description: definition.calculation,
  }));
