import { z } from "zod";

import type { MetricDefinition, MetricValueKind, SourceKey } from "../contracts";

export const metricImplementationStatusSchema = z.enum([
  "CERTIFIABLE",
  "DATA_PENDING",
  "BUSINESS_RULE_REQUIRED",
  "SOURCE_LIMITED",
  "NOT_V1",
]);

export type MetricImplementationStatus = z.infer<typeof metricImplementationStatusSchema>;

export const dashboardSectionSchema = z.enum([
  "Executive Health",
  "Revenue Intelligence",
  "Customer Intelligence",
  "Product Intelligence",
  "Operations Intelligence",
  "Marketing Intelligence",
  "Growth Intelligence",
  "Financial Intelligence",
  "Insights and Data Quality",
]);

export type DashboardSection = z.infer<typeof dashboardSectionSchema>;

export interface MetricCatalogEntry {
  readonly key: string;
  readonly label: string;
  readonly sections: readonly DashboardSection[];
  readonly v1Class: "core" | "future_ready_core" | "conditional" | "not_v1";
  readonly valueKind: MetricValueKind;
  readonly sourceKeys: readonly SourceKey[];
  readonly sources: string;
  readonly sourceFields: string;
  readonly calculation: string;
  readonly status: MetricImplementationStatus;
  readonly blockingReason: string | null;
}

const entry = (value: MetricCatalogEntry): MetricCatalogEntry => Object.freeze(value);

export const metricCatalog = Object.freeze([
  entry({
    key: "commerce.net_sales",
    label: "Net sales",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "net_sales",
    calculation:
      "Pass through Shopify canonical net_sales under the approved DEC-015 revenue policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.orders",
    label: "Orders",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "orders",
    calculation: "Pass through Shopify aggregate orders under the approved DEC-015 order policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.average_order_value",
    label: "Average order value",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "average_order_value",
    calculation:
      "Pass through ShopifyQL average_order_value verbatim; never locally re-divided (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.returning_rate",
    label: "Returning customer rate",
    sections: ["Executive Health", "Customer Intelligence"],
    v1Class: "core",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "returning_customer_rate",
    calculation:
      "Pass through Shopify aggregate customer classification rate; disclose blank classification rows.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.sales_trend",
    label: "Sales trend",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales timeseries",
    sourceFields: "period, net_sales",
    calculation: "Provider-period net-sales points under the approved DEC-015 revenue basis.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.native_channel_mix",
    label: "Native channel mix",
    sections: ["Executive Health", "Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "ShopifyQL native channels and Mappings",
    sourceFields: "sales_channel, net_sales, Mappings",
    calculation:
      "ShopifyQL sales_channel values verbatim under DEC-016; blank or unmatched values remain Unclassified.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "operations.fulfillment_summary",
    label: "Fulfillment summary",
    sections: ["Executive Health", "Operations Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify fulfillment analytics",
    sourceFields: "orders_fulfilled, orders_shipped, orders_delivered",
    calculation:
      "Pass through provider orders_fulfilled/orders_shipped/orders_delivered aggregates with event-dated semantics (DEC-016).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "operations.manufacturer_otif",
    label: "On-time and complete (manufacturer)",
    sections: ["Executive Health", "Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets production and receiving records",
    sourceFields:
      "purchase order, promised date, received date, ordered units, received units, accepted units",
    calculation:
      "Calculate on-time, complete, and damage-free manufacturer delivery rates only from validated received purchase orders under an approved OTIF policy.",
    status: "DATA_PENDING",
    blockingReason:
      "Validated received purchase-order history and the approved manufacturer OTIF policy are not available to the runtime.",
  }),
  entry({
    key: "manufacturing.cogs_per_bar",
    label: "COGS per bar",
    sections: [
      "Executive Health",
      "Product Intelligence",
      "Operations Intelligence",
      "Financial Intelligence",
    ],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Fairafric cost records",
    sourceFields:
      "effective SKU cost, manufactured units, packaging, freight, landed-cost policy, target cost",
    calculation:
      "Calculate landed manufacturing cost per sellable bar only from effective approved cost rows and a reconciled freight and packaging policy.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason:
      "The effective per-bar cost policy, freight treatment, and target cost are not approved.",
  }),
  entry({
    key: "manufacturing.input_cost_movement",
    label: "Input cost movement",
    sections: ["Executive Health", "Operations Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["google_sheets"],
    sources: "Fairafric cost records",
    sourceFields: "effective input, packaging, and freight unit costs by comparable period",
    calculation:
      "Compare effective input costs quarter over quarter only for consistently scoped and validated cost components.",
    status: "DATA_PENDING",
    blockingReason: "Comparable effective input-cost history is not available to the runtime.",
  }),
  entry({
    key: "plan.revenue_variance",
    label: "Revenue versus plan",
    sections: ["Executive Health", "Revenue Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify actuals and Corrected Budget/Forecast plan",
    sourceFields: "approved actual revenue, overlapping plan period",
    calculation: "Actual minus clearly labelled Plan for the same approved period and scope.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason:
      "Actual revenue policy, plan mapping, and comparison behavior remain unapproved.",
  }),
  entry({
    key: "executive.business_health_score",
    label: "Business Health score",
    sections: ["Executive Health"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Multiple approved metrics",
    sourceFields: "approved signals, weights, normalization, thresholds",
    calculation: "Weighted score only after every input and threshold is approved.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Signals, weights, normalization, and thresholds are not approved.",
  }),
  entry({
    key: "executive.recommendations",
    label: "Executive recommendations",
    sections: ["Executive Health", "Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Approved deterministic alerts",
    sourceFields: "active approved alert outputs",
    calculation:
      "Rank only through an approved deterministic ranking policy; never generate AI narrative.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Alert thresholds and ranking policy are not approved.",
  }),
  entry({
    key: "commerce.gross_sales",
    label: "Gross sales",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "gross_sales",
    calculation:
      "Pass through Shopify canonical gross_sales under the approved DEC-015 revenue policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.discounts",
    label: "Discounts",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "discounts",
    calculation:
      "Pass through provider discounts value and sign; never subtracted twice (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.returns",
    label: "Returns",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "returns",
    calculation:
      "Pass through provider returns recognized on the Shopify reporting event date (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.shipping_charges",
    label: "Shipping charges",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "shipping_charges",
    calculation: "Pass through provider shipping charges displayed separately (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.taxes",
    label: "Taxes",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "taxes",
    calculation: "Pass through provider taxes displayed separately (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.total_sales",
    label: "Total sales",
    sections: ["Revenue Intelligence", "Financial Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sales",
    sourceFields: "total_sales",
    calculation: "Pass through Shopify canonical total_sales under the approved DEC-015 policy.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "revenue.dtc_total",
    label: "DTC revenue (total)",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "ShopifyQL sales channels and active Channel_Mapping records",
    sourceFields: "sales_channel, net_sales, effective channel mapping",
    calculation:
      "Sum mapped DTC Site, DTC Affiliate, ShopMy, TikTok Shop, and IG Shop net sales; exclude Events and Unclassified.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "revenue.retail_total",
    label: "Wholesale & in-store revenue",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "ShopifyQL sales channels, Faire records, and active Channel_Mapping records",
    sourceFields: "sales_channel, net_sales, effective channel mapping",
    calculation:
      "Sum mapped Wholesale/Faire, In-store Distribution, and In-store Cafés net sales; exclude Events and Unclassified.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "revenue.channel_mix",
    label: "Revenue by channel",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "ShopifyQL sales channels and active Channel_Mapping records",
    sourceFields: "sales_channel, orders, net_sales, average_order_value, effective mapping",
    calculation:
      "Aggregate provider net sales into the approved ZACAO channel taxonomy; unmatched or ambiguous rows remain Unclassified.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "revenue.channel_margin",
    label: "Contribution margin by channel",
    sections: ["Revenue Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Channel net sales, landed COGS, channel fees, and commission",
    sourceFields: "net product revenue, landed COGS, channel fees, commission",
    calculation:
      "(Net product revenue minus landed COGS, channel fees, and commission) divided by net product revenue.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason:
      "Approved landed COGS, channel-fee, and commission rules are not available for every channel.",
  }),
  entry({
    key: "products.sales",
    label: "Product/SKU sales",
    sections: ["Revenue Intelligence", "Product Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product/variant dimensions",
    sourceFields: "line_type, product_title, product_variant_title, product_variant_sku, net_sales",
    calculation:
      "Merchandise net sales grouped by product/variant/SKU; non-merchandise rows excluded (DEC-015).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.units_sold",
    label: "Units sold",
    sections: ["Revenue Intelligence", "Product Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product line classification",
    sourceFields: "line_type, product_variant_sku, net_items_sold",
    calculation: "Sum net_items_sold for explicitly merchandise-classified rows only.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.purchase_heatmap",
    label: "Purchase heatmap",
    sections: ["Revenue Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL purchase time",
    sourceFields: "day_of_week, hour_of_day, orders",
    calculation: "Qualifying orders grouped by New York day-of-week and hour under DEC-015.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.detailed_order_drilldown",
    label: "Detailed twelve-month order drill-down",
    sections: ["Revenue Intelligence", "Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify Admin GraphQL orders",
    sourceFields: "order and line-item history",
    calculation: "Return sanitized detailed records only when the requested range is complete.",
    status: "DATA_PENDING",
    blockingReason:
      "The PII-safe order-level field contract and drill-down implementation are pending; Shopify read_all_orders access is available.",
  }),
  entry({
    key: "commerce.predictive_forecast",
    label: "Month-end predictive forecast",
    sections: ["Revenue Intelligence"],
    v1Class: "not_v1",
    valueKind: "money",
    sourceKeys: ["shopify"],
    sources: "Future model",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "Predictive forecasting is explicitly outside V1.",
  }),
  entry({
    key: "customers.new_count",
    label: "New customers",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL customer classification",
    sourceFields: "new_or_returning_customer, customers",
    calculation: "Sum Shopify rows classified as new; expose unclassified rows separately.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.returning_count",
    label: "Returning customers",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL customer classification",
    sourceFields: "new_or_returning_customer, customers",
    calculation: "Sum Shopify rows classified as returning; expose unclassified rows separately.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.billing_geography",
    label: "Customer billing geography",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL billing geography",
    sourceFields: "billing_country, billing_region, orders",
    calculation: "PII-free billing country/region aggregates for qualifying orders under DEC-015.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.geo_city",
    label: "Customers by city",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL billing geography",
    sourceFields: "billing_city, billing_region, customers",
    calculation:
      "Rank the top seven usable billing city/region groups by Shopify's provider customer count. Customers are unique within each group and may appear in more than one city group.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "engagement.time_on_site",
    label: "Average time on site",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "duration_seconds",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sessions",
    sourceFields: "average_session_duration",
    calculation:
      "Pass through ShopifyQL average_session_duration in seconds for the requested reporting period; never derive it from session totals.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.age_mix",
    label: "Customer age mix",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo profile attributes",
    sourceFields: "configured age-band profile property",
    calculation:
      "Share of the latest Klaviyo profile snapshot with a declared canonical age band; the selected reporting period does not apply.",
    status: "CERTIFIABLE",
    blockingReason:
      "Configure KLAVIYO_AGE_BAND_PROPERTY and KLAVIYO_GENDER_PROPERTY and grant profiles:read to activate profile demographics.",
  }),
  entry({
    key: "customers.sex_mix",
    label: "Customer gender mix",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo profile attributes",
    sourceFields: "configured gender profile property",
    calculation:
      "Share of the latest Klaviyo profile snapshot by declared gender, preserving source labels and classifying blanks as Undisclosed; the selected reporting period does not apply.",
    status: "CERTIFIABLE",
    blockingReason:
      "Configure KLAVIYO_AGE_BAND_PROPERTY and KLAVIYO_GENDER_PROPERTY and grant profiles:read to activate profile demographics.",
  }),
  entry({
    key: "commerce.web_funnel",
    label: "Shopify acquisition funnel",
    sections: ["Customer Intelligence", "Marketing Intelligence"],
    v1Class: "core",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sessions",
    sourceFields:
      "sessions, online_store_visitors, sessions_with_cart_additions, sessions_that_reached_checkout, sessions_that_completed_checkout, conversion_rate",
    calculation:
      "Expose Shopify provider funnel counts and conversion rate for the requested period.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "commerce.website_sessions",
    label: "Website sessions",
    sections: ["Executive Health", "Customer Intelligence", "Marketing Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sessions",
    sourceFields: "sessions",
    calculation:
      "Pass through the ShopifyQL sessions count for the requested period from the certified acquisition-funnel dataset.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.active",
    label: "Active customers",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Sales_Actuals",
    sourceFields:
      "customer_id, normalized_email fallback, order_date, order_status, gross/net product revenue, is_test, is_sample",
    calculation:
      "Count distinct identified customers with a positive paid, confirmed, or partially-refunded order in the inclusive trailing 90-day window; exclude cancelled, fully refunded, unpaid, test, sample, and zero-value orders.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.cohorts",
    label: "Customer cohorts",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "Detailed customer/order history",
    sourceFields: "customer identity, first order, subsequent orders",
    calculation: "Cohort retention over complete history.",
    status: "SOURCE_LIMITED",
    blockingReason:
      "Cohort retention has not been implemented. The read_all_orders scope needed for complete order history is granted, so this is an implementation gap, not a source limit.",
  }),
  entry({
    key: "customers.realized_ltv",
    label: "Realized LTV",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Sales_Actuals",
    sourceFields:
      "customer_id, order_id, order_date, first_order_date, product revenue and deductions, order_status, acquisition_channel",
    calculation:
      "Net product revenue through the selected end date divided by distinct eligible customers. The start-date, product/SKU, and warehouse filters do not apply.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.realized_ltv_cohorts",
    label: "Customer cohort LTV",
    sections: ["Customer Intelligence"],
    v1Class: "core",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Sales_Actuals and Channel_Mapping",
    sourceFields: "customer identity, first order, product revenue, acquisition channel",
    calculation:
      "Trailing twelve monthly acquisition cohorts at 30, 60, 90, 180 days and lifetime-to-date; immature fixed horizons remain unavailable.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "customers.rfm",
    label: "RFM segmentation",
    sections: ["Customer Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Detailed customer/order history",
    sourceFields: "recency, frequency, monetary history",
    calculation: "Apply approved RFM bands to complete history.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "RFM bands and complete history are unresolved.",
  }),
  entry({
    key: "customers.predictive_churn",
    label: "Predictive churn",
    sections: ["Customer Intelligence"],
    v1Class: "not_v1",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "Future model",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "Predictive churn is explicitly outside V1.",
  }),
  entry({
    key: "products.mix",
    label: "Product mix",
    sections: ["Product Intelligence"],
    v1Class: "core",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product/variant dimensions",
    sourceFields: "net_sales or net_items_sold",
    calculation:
      "Merchandise net-sales share of the merchandise net-sales total, in basis points (DEC-016 net-sales basis).",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.catalog",
    label: "Product price and status",
    sections: ["Product Intelligence"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Shopify Admin GraphQL",
    sourceFields: "Product.id/title/status; Variant.id/SKU/price",
    calculation: "Return current sanitized catalog fields without deriving history.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.units_velocity",
    label: "Units-sold velocity trend",
    sections: ["Product Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product line timeseries",
    sourceFields: "period, line_type, SKU, net_items_sold",
    calculation: "Group merchandise net_items_sold by approved provider period; descriptive only.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "products.sku_velocity",
    label: "SKU velocity",
    sections: ["Product Intelligence"],
    v1Class: "core",
    valueKind: "quantity",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL product line aggregates",
    sourceFields: "canonical SKU, product, net_items_sold",
    calculation:
      "Divide trailing-30-day net merchandise items sold by 30 for each provider SKU; no pack-size conversion is implied.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "inventory.on_hand_bars",
    label: "Inventory on hand by SKU",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify InventoryLevel and Google Sheets SKU_Master",
    sourceFields: "on_hand quantity, canonical SKU, approved bars-per-unit mapping",
    calculation:
      "Convert Shopify on-hand units to canonical bar equivalents only when an approved effective pack mapping exists.",
    status: "DATA_PENDING",
    blockingReason: "Approved production SKU-to-bar mappings are absent.",
  }),
  entry({
    key: "inventory.weeks_cover",
    label: "Weeks of cover",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify inventory and sales plus Google Sheets SKU_Master",
    sourceFields: "sellable bar equivalents and trailing-28-day net bar sales",
    calculation:
      "Divide total sellable bar equivalents by trailing-28-day net bar sales and multiply by four; ratio of totals.",
    status: "DATA_PENDING",
    blockingReason: "Approved production SKU-to-bar mappings are absent.",
  }),
  entry({
    key: "products.sku_margin",
    label: "Margin by SKU",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify sales and approved landed SKU costs",
    sourceFields: "canonical SKU, net sales, net bars sold, effective landed cost",
    calculation:
      "Subtract approved landed COGS from net sales and divide by net sales for each canonical SKU.",
    status: "DATA_PENDING",
    blockingReason: "Approved production landed-cost rows and canonical pack mappings are absent.",
  }),
  entry({
    key: "products.cogs_flags",
    label: "SKUs above COGS target",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Approved landed SKU costs and Metric_Targets",
    sourceFields: "effective landed cost per bar and approved SKU target",
    calculation: "Count active canonical SKUs whose effective landed cost per bar exceeds target.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Approved per-SKU COGS targets are absent.",
  }),
  entry({
    key: "inventory.sku_stock",
    label: "Stock versus ideal band",
    sections: ["Product Intelligence", "Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify inventory and approved Rules_Targets",
    sourceFields: "canonical bar equivalents and effective minimum/maximum stock rules",
    calculation: "Compare current sellable bar-equivalent stock with the approved SKU ideal band.",
    status: "DATA_PENDING",
    blockingReason: "Approved minimum and maximum stock-band rules are absent.",
  }),
  entry({
    key: "manufacturing.cogs_trend",
    label: "Per-bar COGS trend",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Approved COGS_By_SKU and Metric_Targets",
    sourceFields: "effective landed cost per bar and approved target per bar",
    calculation:
      "Return the weighted landed COGS per bar and applicable target by reporting month.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Approved production landed-cost history and per-bar targets are absent.",
  }),
  entry({
    key: "inventory.shopify_current",
    label: "Current Shopify inventory",
    sections: ["Product Intelligence", "Operations Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify Admin GraphQL InventoryLevel",
    sourceFields: "location, quantities available/on_hand/incoming/committed",
    calculation: "Return provider quantities for represented Shopify locations only.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "quality.missing_sku_cost",
    label: "Missing SKU cost",
    sections: ["Product Intelligence", "Insights and Data Quality"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Google Sheets SKU_Master and COGS_By_SKU",
    sourceFields: "active canonical SKU and applicable approved landed/total unit cost",
    calculation:
      "Count active canonical SKUs lacking an applicable positive approved landed/total unit cost.",
    status: "DATA_PENDING",
    blockingReason: "SKU master or applicable approved cost rows are absent.",
  }),
  entry({
    key: "inventory.sell_through",
    label: "Sell-through",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Inventory history/S&OP",
    sourceFields: "opening, receipts, units sold, ending inventory",
    calculation:
      "Net base units sold divided by opening sellable inventory plus warehouse-received sellable units; ratio of totals.",
    status: "DATA_PENDING",
    blockingReason: "Opening inventory, received units, or mapped actual units are absent.",
  }),
  entry({
    key: "inventory.value",
    label: "Inventory value",
    sections: ["Executive Health", "Product Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Inventory and effective SKU_Costs",
    sourceFields: "quantity, canonical-unit mapping, approved effective cost",
    calculation: "Quantity multiplied by approved effective canonical-unit cost.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "inventory.runway_reorder",
    label: "Inventory Runway & Reorder Alert",
    sections: ["Product Intelligence", "Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify units plus Inventory/Forecast/Production/Rules_Targets",
    sourceFields: "complete inventory, velocity, incoming units, lead time, safety buffer",
    calculation:
      "Calculate days-on-hand from sellable inventory and the next four complete approved forecast weeks; reorder remains Phase 2.",
    status: "DATA_PENDING",
    blockingReason: "Four complete future forecast weeks are absent.",
  }),
  entry({
    key: "products.frequently_bought_together",
    label: "Frequently bought together",
    sections: ["Product Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "Detailed order line history",
    sourceFields: "complete order-product pairs",
    calculation: "Calculate product-pair support/confidence under approved thresholds.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Detailed history and pair thresholds are unresolved.",
  }),
  entry({
    key: "operations.shipped_delivered",
    label: "Shipped and delivered counts",
    sections: ["Operations Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "Shopify fulfillment analytics",
    sourceFields: "orders_shipped, orders_delivered",
    calculation: "Return provider aggregates with an explicit partial-coverage warning.",
    status: "SOURCE_LIMITED",
    blockingReason: "Carrier event coverage is not complete enough for a complete-company claim.",
  }),
  entry({
    key: "operations.manufacturer_lead_time",
    label: "Average manufacturer lead time",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Production_Orders",
    sourceFields: "confirmed date, final receipt date, non-cancelled purchase order",
    calculation:
      "Mean calendar days from confirmed date through final receipt for eligible received purchase orders.",
    status: "DATA_PENDING",
    blockingReason: "Confirmed dates and complete received purchase-order history are absent.",
  }),
  entry({
    key: "operations.warehouse_on_time_accuracy",
    label: "Warehouse on-time & accurate",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Warehouse_Fulfillment",
    sourceFields: "opaque order, warehouse, promised and actual ship timestamps, pick accuracy",
    calculation:
      "Orders shipped in the selected period that met both ship-time and pick-accuracy conditions divided by complete shipped records.",
    status: "DATA_PENDING",
    blockingReason: "Certified warehouse fulfillment records are absent.",
  }),
  entry({
    key: "operations.refund_rate",
    label: "Refund rate",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify"],
    sources: "Shopify detailed order and refund history",
    sourceFields: "created date, test/cancelled state, refund records, pagination completeness",
    calculation:
      "Non-test, non-cancelled orders created in the selected period with any recorded refund divided by the eligible order cohort.",
    status: "CERTIFIABLE",
    blockingReason:
      "Complete detailed order and refund history is required for the selected cohort.",
  }),
  entry({
    key: "operations.manufacturer_performance",
    label: "Manufacturer delivery performance",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Production_Orders",
    sourceFields: "due date, receipt date, ordered, received, and accepted units",
    calculation:
      "Expose on-time and complete rates for purchase orders due in the selected period plus damage-free coverage for received purchase orders.",
    status: "DATA_PENDING",
    blockingReason: "Eligible production-order and receiving records are absent.",
  }),
  entry({
    key: "inventory.stock_health",
    label: "Stock level health",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify inventory, SKU_Master, and effective ideal bands",
    sourceFields: "active canonical SKU, bar-equivalent stock, approved minimum and maximum",
    calculation: "Report active SKUs inside complete approved bands divided by all active SKUs.",
    status: "DATA_PENDING",
    blockingReason: "Complete effective stock-band rules for all active SKUs are absent.",
  }),
  entry({
    key: "inventory.packaging_stock",
    label: "Packaging material stock",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Packaging_Materials, Packaging_Inventory, and Packaging_Orders",
    sourceFields: "material, unit, effective ideal band, latest stock, incoming quantity and ETA",
    calculation:
      "Compare each active material's latest certified stock with its effective ideal band.",
    status: "DATA_PENDING",
    blockingReason:
      "Certified packaging material, stock, band, and incoming-order coverage is absent.",
  }),
  entry({
    key: "inventory.packaging_projection",
    label: "Packaging stock projection",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets packaging inventory, orders, and approved forecast",
    sourceFields: "latest stock, dated incoming quantities, approved monthly consumption",
    calculation:
      "Project four complete months as prior ending stock plus certified incoming POs minus approved consumption without clamping negatives.",
    status: "DATA_PENDING",
    blockingReason:
      "Complete active-material stock and approved four-month forecast coverage is absent.",
  }),
  entry({
    key: "production.delivery_timeline",
    label: "Projected delivery timeline",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Production_Orders",
    sourceFields: "purchase order, item, production start, expected arrival, quantity and status",
    calculation:
      "Render active purchase orders with both production-start and expected-arrival dates.",
    status: "DATA_PENDING",
    blockingReason:
      "Active production rows with complete start and expected-arrival dates are absent.",
  }),
  entry({
    key: "inventory.combined",
    label: "Combined SNAPL/YBYD inventory",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify plus Google Sheets Inventory_Snapshots",
    sourceFields: "dated warehouse/SKU quantities and mappings",
    calculation: "Combine only complete mapped location snapshots without double-counting overlap.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION inventory/mapping rows are empty.",
  }),
  entry({
    key: "inventory.lots",
    label: "Lot and best-by visibility",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Inventory_Lots and S&OP reference",
    sourceFields: "warehouse, SKU, lot, best-by, quantity, status",
    calculation:
      "Return validated current lot rows and quantities; no movement history is inferred.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION lot records are empty.",
  }),
  entry({
    key: "inventory.fefo",
    label: "FEFO visibility",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["google_sheets"],
    sources: "Inventory_Lots and Depletions",
    sourceFields: "lot best-by, availability, lot-linked depletion",
    calculation:
      "Evaluate only under an approved FEFO rule and sufficiently linked depletion records.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "FEFO rule and complete lot-linked depletion data are absent.",
  }),
  entry({
    key: "forecast.variance",
    label: "Forecast versus actual",
    sections: ["Operations Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "PRODUCTION Forecast plus Shopify actuals",
    sourceFields: "single valid Active forecast version, period/SKU/channel actual units",
    calculation: "Actual units minus forecast units for identical period/SKU/channel scope.",
    status: "DATA_PENDING",
    blockingReason:
      "PRODUCTION forecast and required mappings are empty; actual policy may further limit revenue variance.",
  }),
  entry({
    key: "production.incoming",
    label: "Incoming production",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Production_Orders and S&OP reference",
    sourceFields: "PO line, SKU, units, arrival, status, destination",
    calculation:
      "Return validated PO-line exposure and received quantities without inventing schedule events.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION production rows are empty.",
  }),
  entry({
    key: "production.timeline",
    label: "Production timeline",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "PRODUCTION Production and S&OP reference",
    sourceFields: "order/production/arrival dates and status",
    calculation: "Return validated current PO milestones; no event history is inferred.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION rows are empty and the S&OP schedule remains unreliable.",
  }),
  entry({
    key: "production.cost_payment",
    label: "Production cost and payment exposure",
    sections: ["Operations Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "PRODUCTION Production; Budget/S&OP plan references",
    sourceFields: "PO unit/freight/deposit/balance values and dates",
    calculation: "Sum validated PO exposure separately from actual expenses and realized COGS.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION PO values are empty; reference-source cost conflicts remain.",
  }),
  entry({
    key: "inventory.depletions",
    label: "Additional depletions",
    sections: ["Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Additional_Depletions",
    sourceFields: "date, warehouse, SKU, quantity, reason",
    calculation: "Sum validated non-revenue depletion events by requested dimensions.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION depletion records are empty.",
  }),
  entry({
    key: "klaviyo.email_overview",
    label: "Email performance overview",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields:
      "recipients, delivered/rate, opens_unique/rate, clicks_unique/rate, click_to_open_rate, bounced/rate, unsubscribe_uniques/rate, spam complaints/rate",
    calculation: "Expose verified Reporting API statistics with send-date semantics.",
    status: "DATA_PENDING",
    blockingReason:
      "The audited account has no report/event activity and live credentials are deferred.",
  }),
  entry({
    key: "klaviyo.email_recipients",
    label: "Email recipients",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "recipients",
    calculation: "Pass through the report recipient count using send-date semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_delivery_rate",
    label: "Email delivery rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "delivery_rate",
    calculation: "Pass through the verified report delivery rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_open_rate",
    label: "Email open rate",
    sections: ["Customer Intelligence", "Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "open_rate",
    calculation: "Pass through the verified report open rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_click_rate",
    label: "Email click rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "click_rate",
    calculation: "Pass through the verified report click rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_click_to_open_rate",
    label: "Email click-to-open rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "click_to_open_rate",
    calculation: "Pass through the verified report click-to-open rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_bounce_rate",
    label: "Email bounce rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "bounce_rate",
    calculation: "Pass through the verified report bounce rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_unsubscribe_rate",
    label: "Email unsubscribe rate",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "unsubscribe_rate",
    calculation: "Pass through the verified report unsubscribe rate.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.email_spam_complaints",
    label: "Email spam complaints",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo Reporting API",
    sourceFields: "spam_complaints",
    calculation: "Pass through the verified report complaint count.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no report activity.",
  }),
  entry({
    key: "klaviyo.sms_overview",
    label: "SMS performance overview",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo reports and selected metrics",
    sourceFields: "sent, received/delivered, clicked, failed, unsubscribed",
    calculation: "Expose supported verified SMS report/aggregate values with their time semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity and live credentials are deferred.",
  }),
  entry({
    key: "klaviyo.sms_sent",
    label: "SMS sent",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Sent Text Message / report recipients",
    calculation: "Expose the verified source count with its report/event-time label.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_delivered",
    label: "SMS delivered or received",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Received Text Message / supported delivery statistic",
    calculation:
      "Expose only the exact supported delivered/received measure and label it accordingly.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_clicked",
    label: "SMS clicked",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Clicked Text Message",
    calculation: "Expose the verified click count with its time semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_failed",
    label: "SMS failed",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Failed to Deliver Text Message",
    calculation: "Expose the verified failed-delivery count.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.sms_unsubscribed",
    label: "SMS unsubscribed",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo verified metric/report",
    sourceFields: "Unsubscribed from Text Messaging Marketing",
    calculation: "Expose the verified SMS unsubscribe count.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no SMS activity.",
  }),
  entry({
    key: "klaviyo.campaign_performance",
    label: "Campaign performance",
    sections: ["Customer Intelligence", "Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "status",
    sourceKeys: ["klaviyo"],
    sources: "campaign-values-reports",
    sourceFields: "campaign/message/channel groupings and verified report statistics",
    calculation:
      "Map each report row to a sanitized table; report values retain send-date semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no campaigns/report rows.",
  }),
  entry({
    key: "klaviyo.flow_performance",
    label: "Flow performance",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "status",
    sourceKeys: ["klaviyo"],
    sources: "flow-values-reports",
    sourceFields: "flow/message/channel groupings and verified report statistics",
    calculation:
      "Map each report row to a sanitized table; report values retain send-date semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited flows currently have no report rows.",
  }),
  entry({
    key: "klaviyo.attributed_revenue",
    label: "Klaviyo-attributed revenue",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "money",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo report conversion value",
    sourceFields: "conversion_value for verified Placed Order metric",
    calculation: "Expose only as Klaviyo-attributed revenue under Klaviyo attribution semantics.",
    status: "DATA_PENDING",
    blockingReason:
      "No report data exists; attribution settings must be recorded before production readiness.",
  }),
  entry({
    key: "klaviyo.engagement_trend",
    label: "Klaviyo engagement trend",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo metric-aggregates",
    sourceFields: "dates and count/unique/sum_value measurements",
    calculation: "Return event-time trend points normalized to America/New_York display periods.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no events and live credentials are deferred.",
  }),
  entry({
    key: "klaviyo.email_funnel",
    label: "Email conversion funnel",
    sections: ["Marketing Intelligence"],
    v1Class: "future_ready_core",
    valueKind: "count",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo campaign and flow values reports",
    sourceFields: "recipients, delivered, opens_unique, clicks_unique and provider rates",
    calculation:
      "Show audited email stage counts with delivery, open, and click rates under Klaviyo send-date semantics.",
    status: "DATA_PENDING",
    blockingReason: "The audited account has no email report rows.",
  }),
  entry({
    key: "marketing.spend",
    label: "Marketing spend",
    sections: ["Marketing Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Marketing_Spend",
    sourceFields: "date, platform, campaign, spend USD",
    calculation:
      "Sum validated spend rows by requested period/dimensions; do not infer attribution.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION marketing-spend rows are empty.",
  }),
  entry({
    key: "marketing.cac",
    label: "Customer acquisition cost",
    sections: ["Customer Intelligence", "Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Approved spend and acquisition attribution",
    sourceFields: "approved spend numerator and acquired-customer denominator",
    calculation:
      "Numerator divided by denominator only under an approved blended/attributed policy.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Numerator, denominator, and acquisition attribution are not approved.",
  }),
  entry({
    key: "marketing.roas",
    label: "ROAS",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["klaviyo", "google_sheets"],
    sources: "Approved attributed revenue and spend",
    sourceFields: "approved attributed-revenue numerator and spend denominator",
    calculation:
      "Attributed revenue divided by matching spend only under an approved attribution policy.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Revenue attribution and spend scope are not approved.",
  }),
  entry({
    key: "marketing.ltv_cac",
    label: "LTV:CAC",
    sections: ["Customer Intelligence", "Marketing Intelligence", "Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "klaviyo", "google_sheets"],
    sources: "Approved LTV and CAC",
    sourceFields: "approved LTV numerator and CAC denominator",
    calculation: "Approved LTV divided by approved CAC for an identical scope.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Both LTV and CAC policies are unresolved.",
  }),
  entry({
    key: "social.performance",
    label: "Social Audience Growth",
    sections: ["Marketing Intelligence", "Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Social_Metrics",
    sourceFields: "dated platform/account followers and optional engagement measures",
    calculation:
      "Return validated dated observations; missing optional measures remain unavailable.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION social records are empty.",
  }),
  entry({
    key: "social.followers_total",
    label: "Total followers",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Social_Metrics",
    sourceFields: "snapshot_date, platform, account, followers",
    calculation: "Sum each maintained platform/account's latest observation at period end.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION follower snapshots are empty.",
  }),
  entry({
    key: "social.follower_growth",
    label: "Follower growth by channel",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Social_Metrics",
    sourceFields: "dated follower observations for Instagram, TikTok, and YouTube",
    calculation: "Return month-end as-of follower totals without future-value carryback.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION follower history is empty.",
  }),
  entry({
    key: "social.channel_performance",
    label: "Social channel performance",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Social_Metrics and Social_Channel_Performance",
    sourceFields:
      "followers, growth, audience reach, attributed net sales and attribution reference",
    calculation: "Join certified channel snapshots to non-overlapping period performance records.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION social channel records are empty.",
  }),
  entry({
    key: "social.mentions_by_channel",
    label: "Social mentions by channel",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Social_Channel_Performance",
    sourceFields: "period, platform, recorded mentions",
    calculation:
      "Sum non-overlapping certified mention records by platform in the selected period.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION mention records are empty.",
  }),
  entry({
    key: "collabs.active",
    label: "Active brand collaborations",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Growth_Pipeline",
    sourceFields: "collaboration lifecycle and effective dates",
    calculation: "Count Live or In production collaborations overlapping the selected period.",
    status: "DATA_PENDING",
    blockingReason: "Certified collaboration lifecycle records are empty.",
  }),
  entry({
    key: "collabs.reach",
    label: "Collaboration reach",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Growth_Pipeline",
    sourceFields: "partner, lifecycle, audience reach, category and launch date",
    calculation: "Rank Live, In production, and Scheduled collaboration pipeline rows by reach.",
    status: "DATA_PENDING",
    blockingReason: "Certified collaboration reach records are empty.",
  }),
  entry({
    key: "collabs.by_category",
    label: "Collaborations by category",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Growth_Pipeline",
    sourceFields: "collaboration category and lifecycle",
    calculation:
      "Count Live, In production, and Scheduled collaboration rows by approved category.",
    status: "DATA_PENDING",
    blockingReason: "Certified collaboration categories are empty.",
  }),
  entry({
    key: "traffic.attribution",
    label: "Web traffic by source",
    sections: ["Marketing Intelligence"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify"],
    sources: "ShopifyQL sessions",
    sourceFields: "human sessions grouped by provider referrer_source",
    calculation:
      "Preserve provider classifications, route blanks to Unclassified, and rank by sessions.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "ambassadors.active",
    label: "Active ambassadors",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Affiliate_Ambassador_Perf",
    sourceFields: "partner type, reporting period, tracked clicks and payout status",
    calculation: "Count distinct non-cancelled ambassadors with at least one tracked click.",
    status: "DATA_PENDING",
    blockingReason: "Certified ambassador performance records are empty.",
  }),
  entry({
    key: "ambassadors.sessions",
    label: "Affiliate-driven sessions",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets", "shopify"],
    sources: "Affiliate UTM mappings and ShopifyQL sessions",
    sourceFields: "exact utm_source, utm_campaign, utm_content tuple and sessions",
    calculation: "Sum sessions matched through unique, exact affiliate UTM mappings.",
    status: "DATA_PENDING",
    blockingReason: "Certified affiliate UTM mappings or matching sessions are unavailable.",
  }),
  entry({
    key: "ambassadors.revenue",
    label: "Affiliate-driven revenue",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets", "shopify"],
    sources: "Affiliate discount-code mappings and Shopify sales",
    sourceFields: "exact discount code, orders and net sales",
    calculation: "Sum provider net sales matched through unique, exact ambassador-code mappings.",
    status: "DATA_PENDING",
    blockingReason: "Certified affiliate-code mappings or matching Shopify sales are unavailable.",
  }),
  entry({
    key: "ambassadors.top",
    label: "Top ambassadors",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["google_sheets", "shopify"],
    sources: "Affiliate_Ambassador_Perf and matched Shopify sessions/sales",
    sourceFields: "ambassador, code, clicks, commission, orders and net sales",
    calculation: "Rank mapped ambassadors by certified attributed net sales.",
    status: "DATA_PENDING",
    blockingReason: "Certified ambassador performance rows are empty.",
  }),
  entry({
    key: "marketing.affiliate_roi_message",
    label: "Affiliate ROI by message",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets", "shopify"],
    sources: "Approved affiliate attribution, commission, spend, and messaging taxonomy",
    sourceFields: "attributed net sales, commission, spend and approved message category",
    calculation:
      "Attributed net sales divided by commission plus spend only after policy approval.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason:
      "Affiliate message taxonomy, spend scope, and ROI attribution are not approved.",
  }),
  entry({
    key: "marketing.campaign_roi",
    label: "Campaign ROI",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "quantity",
    sourceKeys: ["google_sheets"],
    sources: "Approved campaign spend and attributed net sales",
    sourceFields: "matching campaign spend, revenue attribution, model and window",
    calculation: "Attributed net sales divided by campaign spend only after policy approval.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Campaign revenue attribution and matching spend scope are not approved.",
  }),
  entry({
    key: "marketing.content_conversion",
    label: "Content conversion",
    sections: ["Marketing Intelligence"],
    v1Class: "conditional",
    valueKind: "rate_basis_points",
    sourceKeys: ["shopify", "klaviyo"],
    sources: "GA4/ad/content tracking",
    sourceFields: "content identifiers and verified attribution",
    calculation: "No V1 calculation without verified tracking and attribution.",
    status: "SOURCE_LIMITED",
    blockingReason: "GA4/ad access and content tagging are not available.",
  }),
  entry({
    key: "sources.freshness",
    label: "Source freshness",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["shopify", "klaviyo", "google_drive", "google_sheets"],
    sources: "All source-status contracts",
    sourceFields: "checkedAt, lastSuccessfulAt, dataAsOf, source state",
    calculation:
      "Expose verifiable source timestamps/states without equating file modification with business freshness.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "sources.historical_completeness",
    label: "Historical completeness",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Shopify history contract",
    sourceFields: "mode, requested range, earliest detailed record, completeness",
    calculation: "Expose aggregate-versus-detailed history and complete-for-request status.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "quality.unclassified_channel",
    label: "Unclassified channel",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "count",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify channel values and Mappings",
    sourceFields: "source channel plus effective mapping",
    calculation: "Count only against an approved effective source-channel mapping table.",
    status: "DATA_PENDING",
    blockingReason: "An active canonical channel mapping table is required.",
  }),
  entry({
    key: "quality.klaviyo_no_activity",
    label: "Klaviyo no-data state",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["klaviyo"],
    sources: "Klaviyo source status",
    sourceFields: "connection, event/report presence",
    calculation:
      "Return No activity when valid configured reads contain no genuine events/reports.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "quality.sop_validation",
    label: "S&OP validation",
    sections: ["Insights and Data Quality"],
    v1Class: "core",
    valueKind: "status",
    sourceKeys: ["google_drive"],
    sources: "Allowlisted S&OP workbook inspection",
    sourceFields: "formula errors, broken references, examples, placeholders, blank inputs",
    calculation:
      "Expose detected formula errors/placeholders without repairing or treating them as actuals.",
    status: "CERTIFIABLE",
    blockingReason: null,
  }),
  entry({
    key: "alerts.low_inventory",
    label: "Low inventory alert",
    sections: ["Insights and Data Quality", "Product Intelligence"],
    v1Class: "not_v1",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Inventory and Rules_Targets",
    sourceFields: "on-hand quantity and complete approved per-SKU thresholds",
    calculation: "Compare inventory to an effective approved threshold only.",
    status: "NOT_V1",
    blockingReason: "Low-inventory thresholds and reorder recommendations are Phase 2.",
  }),
  entry({
    key: "alerts.conversion_decline",
    label: "Conversion decline alert",
    sections: ["Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify funnel and Rules_Targets",
    sourceFields: "comparable conversion periods and approved threshold",
    calculation: "Evaluate equivalent periods only under an approved threshold/comparison rule.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Comparison and threshold policy is absent.",
  }),
  entry({
    key: "alerts.refund_increase",
    label: "Refund increase alert",
    sections: ["Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify returns/refunds and Rules_Targets",
    sourceFields: "approved refund metric/comparison and threshold",
    calculation: "Evaluate only after refund policy and threshold approval.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Refund definition, comparison, and threshold are absent.",
  }),
  entry({
    key: "alerts.fulfillment_backlog",
    label: "Fulfillment backlog alert",
    sections: ["Insights and Data Quality"],
    v1Class: "conditional",
    valueKind: "status",
    sourceKeys: ["shopify", "google_sheets"],
    sources: "Shopify orders/fulfillments and Rules_Targets",
    sourceFields: "approved unfulfilled status, age, threshold",
    calculation: "Evaluate only under approved backlog age/status thresholds.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "Backlog status, age, and threshold policy is absent.",
  }),
  entry({
    key: "actions.assign",
    label: "Assign action",
    sections: ["Insights and Data Quality"],
    v1Class: "not_v1",
    valueKind: "status",
    sourceKeys: ["google_sheets"],
    sources: "Write workflow",
    sourceFields: "not applicable",
    calculation: "Not implemented in read-only V1.",
    status: "NOT_V1",
    blockingReason: "Would require an unauthorized write workflow.",
  }),
  entry({
    key: "recommendations.ai",
    label: "AI-generated recommendations",
    sections: ["Insights and Data Quality"],
    v1Class: "not_v1",
    valueKind: "status",
    sourceKeys: ["shopify"],
    sources: "Future AI system",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "AI-generated recommendations are explicitly outside V1.",
  }),
  entry({
    key: "partners.performance",
    label: "Partner performance",
    sections: ["Growth Intelligence"],
    v1Class: "not_v1",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Affiliate_Ambassador_Perf",
    sourceFields: "period, type, partner, platform, optional orders/revenue/commission",
    calculation: "Phase 2 only; no V1 partner attribution result is calculated.",
    status: "NOT_V1",
    blockingReason: "Partner attribution priority and net-revenue inputs are Phase 2.",
  }),
  entry({
    key: "growth.open_pipeline",
    label: "Open pipeline",
    sections: ["Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Growth_Pipeline",
    sourceFields: "pipeline type, opportunity, status, optional value",
    calculation:
      "Count distinct live nonterminal opportunities; retain stated values only as supporting next-action detail.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION growth-pipeline rows are empty.",
  }),
  entry({
    key: "growth.pipeline_by_type",
    label: "Pipeline by category",
    sections: ["Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "count",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Growth_Pipeline",
    sourceFields: "pipeline type, status, optional value",
    calculation: "Group validated current opportunities by pipeline type and status.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION growth-pipeline rows are empty.",
  }),
  entry({
    key: "growth.next_actions",
    label: "Pipeline next actions",
    sections: ["Growth Intelligence"],
    v1Class: "conditional",
    valueKind: "date",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Growth_Pipeline",
    sourceFields: "opportunity, next action, due date, value",
    calculation:
      "Return supplied current next actions ordered by due date; do not rank by invented probability.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION growth-pipeline rows are empty.",
  }),
  entry({
    key: "growth.weighted_pipeline",
    label: "Weighted pipeline",
    sections: ["Growth Intelligence"],
    v1Class: "not_v1",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Future approved probability source",
    sourceFields: "value and approved probability",
    calculation: "Not calculated from the simplified V1 source contract.",
    status: "NOT_V1",
    blockingReason:
      "The approved simplified Growth_Pipeline has no probability field; predictive probability is outside V1.",
  }),
  entry({
    key: "finance.actual_expenses",
    label: "Actual operating expenses",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Finance_Actuals",
    sourceFields: "date, category, amount USD",
    calculation: "Sum validated actual-expense rows, including explicit negative correction rows.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION finance-actual rows are empty.",
  }),
  entry({
    key: "finance.expense_composition",
    label: "Expense composition",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Finance_Actuals",
    sourceFields: "category, amount USD",
    calculation: "Group validated actual expenses by approved category.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION finance-actual rows are empty.",
  }),
  entry({
    key: "finance.cash_position",
    label: "Cash position",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Google Sheets Cash_Position",
    sourceFields: "latest dated account balance and restricted cash",
    calculation:
      "Return latest validated account balances; unrestricted totals require complete account coverage.",
    status: "DATA_PENDING",
    blockingReason: "PRODUCTION cash rows are empty and completeness is not established.",
  }),
  entry({
    key: "finance.budget_vs_actual",
    label: "Budget versus actual",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "Corrected Budget plan and PRODUCTION actuals",
    sourceFields: "mapped plan and actual categories/periods",
    calculation:
      "Actual minus Plan for identical approved categories and periods, with labels preserved.",
    status: "DATA_PENDING",
    blockingReason: "Actual rows and approved plan/actual category mappings are absent.",
  }),
  entry({
    key: "finance.actual_margin",
    label: "Actual Gross Margin",
    sections: ["Financial Intelligence", "Product Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["shopify", "google_sheets", "google_drive"],
    sources: "Eligible Shopify product revenue and corrected Budget V5 SKU COGS",
    sourceFields: "net product revenue, sold SKU quantities, approved effective SKU COGS",
    calculation:
      "Actual Gross Margin = Net Product Revenue minus approved SKU COGS; never impute missing COGS as zero and disclose sold-SKU COGS coverage.",
    status: "DATA_PENDING",
    blockingReason:
      "Corrected Budget V5 and complete sold-SKU quantity/cost coverage are not available to the runtime.",
  }),
  entry({
    key: "finance.monthly_burn",
    label: "Monthly Net Burn",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "PRODUCTION Finance_Actuals",
    sourceFields: "cleared operating cash inflows/outflows and approved operating categories",
    calculation:
      "Cash-basis operating outflows minus operating inflows, with inventory payments included once and accounting COGS excluded from duplicate counting.",
    status: "DATA_PENDING",
    blockingReason:
      "Finance_Actuals does not yet provide complete cleared cash direction and operating-scope history.",
  }),
  entry({
    key: "finance.cash_runway",
    label: "Cash runway",
    sections: ["Financial Intelligence"],
    v1Class: "conditional",
    valueKind: "duration_seconds",
    sourceKeys: ["google_sheets"],
    sources: "PRODUCTION Cash and approved burn",
    sourceFields:
      "cleared unrestricted balances and trailing three complete months of net cash burn",
    calculation:
      "Unrestricted available cash divided by trailing three-month average net cash burn; return 'No current net burn' for zero/negative burn and unavailable for incomplete inputs.",
    status: "DATA_PENDING",
    blockingReason:
      "A complete trailing three-month cash-burn series is not available to the runtime.",
  }),
  entry({
    key: "finance.fairafric_rebate",
    label: "Fairafric rebate",
    sections: ["Financial Intelligence", "Operations Intelligence"],
    v1Class: "conditional",
    valueKind: "money",
    sourceKeys: ["google_sheets", "google_drive"],
    sources: "Production rows and Rules_Targets",
    sourceFields: "qualifying units/PO plus approved rebate parameters",
    calculation: "Apply only a signed/effective approved rebate rule.",
    status: "BUSINESS_RULE_REQUIRED",
    blockingReason: "No approved rebate rule registry exists.",
  }),
  entry({
    key: "finance.predictive_cashflow",
    label: "Predictive cash flow",
    sections: ["Financial Intelligence"],
    v1Class: "not_v1",
    valueKind: "money",
    sourceKeys: ["google_sheets"],
    sources: "Future model",
    sourceFields: "not applicable",
    calculation: "Not implemented in V1.",
    status: "NOT_V1",
    blockingReason: "Predictive cash-flow modelling is explicitly outside V1.",
  }),
] satisfies readonly MetricCatalogEntry[]);

export function metricCatalogEntry(key: string): MetricCatalogEntry | undefined {
  return metricCatalog.find((definition) => definition.key === key);
}

export const activeMetricDefinitions: readonly MetricDefinition[] = metricCatalog
  .filter((definition) => definition.v1Class !== "not_v1")
  .map((definition) => ({
    key: definition.key,
    schemaVersion: "1.0" as const,
    definitionVersion: "1.0",
    classification: definition.v1Class as "core" | "future_ready_core" | "conditional",
    valueKind: definition.valueKind,
    sourceKeys: [...definition.sourceKeys],
    description: definition.calculation,
  }));
