// GENERATED FILE — do not edit by hand.
// Source of truth: tests/fixtures/manual-workbook/ZACAO_Dashboard_V1_Input_Workbook.xlsx
// (Data_Dictionary + Lists tabs). Regenerate with: node scripts/db/generate-contracts.mjs

export type ManualColumnKind =
  "text" | "date" | "timestamp" | "integer" | "usd" | "decimal" | "percent";

export interface ManualColumnContract {
  readonly header: string;
  readonly kind: ManualColumnKind;
  readonly required: boolean;
  readonly enumValues?: readonly string[];
}

export interface ManualTabContract {
  readonly name: string;
  readonly tableName: string;
  readonly businessKey: readonly string[];
  readonly columns: readonly ManualColumnContract[];
}

export const MANUAL_WORKBOOK_TABS = [
  "SKU_Master",
  "Location_Master",
  "Source_Registry",
  "Channel_Mapping",
  "Sales_Actuals",
  "Inventory_Snapshots",
  "Inventory_Lots",
  "Sales_Forecast",
  "Production_Orders",
  "Production_Schedule",
  "Additional_Depletions",
  "COGS_By_SKU",
  "Finance_Actuals",
  "Cash_Position",
  "Marketing_Spend",
  "Social_Metrics",
  "Affiliate_Ambassador_Perf",
  "Growth_Pipeline",
  "Metric_Targets",
] as const;

export type ManualWorkbookTab = (typeof MANUAL_WORKBOOK_TABS)[number];

export const SOURCE_STATUS_COLUMN = "source_status" as const;
export const PRODUCTION_SOURCE_STATUS = "production" as const;

export const CONTROLLED_LISTS: Readonly<Record<string, readonly string[]>> = {
  sku_id: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
  warehouse: ["SNAPL 3PL", "YBYD", "139 North 10th Street", "In Transit", "Other"],
  dashboard_channel: [
    "DTC (Shopify)",
    "Amazon FBA",
    "TikTok Shop",
    "Retail / Wholesale",
    "Distributor",
    "Unclassified",
  ],
  sop_channel: ["D2C / Website", "Retail", "Wholesale", "Not mapped"],
  source_system: [
    "shopify",
    "klaviyo",
    "amazon",
    "tiktok",
    "budget",
    "sop",
    "manual",
    "bank",
    "other",
  ],
  source_status: ["production", "draft", "example", "invalid"],
  status_mapping: ["active", "inactive", "superseded"],
  status_forecast: ["draft", "submitted", "approved", "superseded"],
  status_po: [
    "draft",
    "open",
    "confirmed",
    "in_production",
    "in_transit",
    "partially_received",
    "received",
    "cancelled",
  ],
  status_schedule: ["planned", "in_progress", "completed", "on_hold", "cancelled"],
  status_lot: [
    "in_transit",
    "received",
    "in_stock",
    "quarantine",
    "depleted",
    "expired",
    "written_off",
  ],
  status_finance: ["draft", "posted", "reconciled", "adjusted"],
  status_target: ["active", "inactive", "achieved", "missed"],
  payout_status: ["pending", "approved", "paid", "on_hold", "cancelled"],
  depletion_reason: [
    "gifting",
    "sample",
    "influencer_seeding",
    "promotion",
    "event",
    "wastage",
    "damage",
    "quality_hold",
    "internal_use",
    "other",
  ],
  cost_basis: ["standard", "actual", "landed", "quoted"],
  cash_or_accrual: ["cash", "accrual"],
  pipeline_type: ["retail", "collaboration", "partnership", "investor", "grant"],
  pipeline_stage: [
    "prospect",
    "contacted",
    "in_discussion",
    "proposal_sent",
    "negotiation",
    "won",
    "lost",
    "on_hold",
  ],
  pipeline_status: ["open", "won", "lost", "stalled"],
  ad_platform: ["meta", "tiktok", "google", "amazon_ads", "pinterest", "klaviyo", "other"],
  social_platform: [
    "instagram",
    "tiktok",
    "youtube",
    "linkedin",
    "x",
    "facebook",
    "pinterest",
    "other",
  ],
  partner_platform: ["instagram", "tiktok", "youtube", "campus", "web", "email", "other"],
  target_unit: ["usd", "units", "percent", "ratio", "count", "days"],
  target_scope: ["company", "channel", "sku", "location", "campaign"],
  yes_no: ["yes", "no"],
  currency: ["USD"],
  order_status: ["paid", "confirmed", "partially_refunded", "refunded", "cancelled", "unpaid"],
};

export const MANUAL_TAB_CONTRACTS: Readonly<Record<ManualWorkbookTab, ManualTabContract>> = {
  SKU_Master: {
    name: "SKU_Master",
    tableName: "sku_master",
    businessKey: ["sku_id"],
    columns: [
      { header: "sku_id", kind: "text", required: true },
      { header: "canonical_name", kind: "text", required: true },
      { header: "recipe_doc_name", kind: "text", required: false },
      { header: "po_sales_order_name", kind: "text", required: false },
      { header: "shopify_product_title", kind: "text", required: false },
      { header: "shopify_variant_title", kind: "text", required: false },
      { header: "shopify_variant_sku", kind: "text", required: false },
      { header: "pack_size_bars", kind: "integer", required: false },
      { header: "is_active", kind: "text", required: false, enumValues: ["yes", "no"] },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Location_Master: {
    name: "Location_Master",
    tableName: "location_master",
    businessKey: ["location_id"],
    columns: [
      { header: "location_id", kind: "text", required: true },
      { header: "location_name", kind: "text", required: true },
      { header: "location_type", kind: "text", required: false },
      { header: "shopify_location_name", kind: "text", required: false },
      { header: "address", kind: "text", required: false },
      { header: "is_active", kind: "text", required: false, enumValues: ["yes", "no"] },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Source_Registry: {
    name: "Source_Registry",
    tableName: "source_registry",
    businessKey: ["source_id"],
    columns: [
      { header: "source_id", kind: "text", required: true },
      {
        header: "source_system",
        kind: "text",
        required: true,
        enumValues: [
          "shopify",
          "klaviyo",
          "amazon",
          "tiktok",
          "budget",
          "sop",
          "manual",
          "bank",
          "other",
        ],
      },
      { header: "source_name", kind: "text", required: true },
      { header: "file_id_or_account", kind: "text", required: true },
      { header: "tab_name", kind: "text", required: false },
      { header: "allowlisted", kind: "text", required: true, enumValues: ["yes", "no"] },
      { header: "refresh_frequency", kind: "text", required: false },
      { header: "max_staleness", kind: "text", required: false },
      { header: "owner", kind: "text", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Channel_Mapping: {
    name: "Channel_Mapping",
    tableName: "channel_mapping",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      {
        header: "source_system",
        kind: "text",
        required: true,
        enumValues: [
          "shopify",
          "klaviyo",
          "amazon",
          "tiktok",
          "budget",
          "sop",
          "manual",
          "bank",
          "other",
        ],
      },
      { header: "source_channel_or_name", kind: "text", required: true },
      { header: "order_tag", kind: "text", required: false },
      { header: "discount_code", kind: "text", required: false },
      { header: "utm_source", kind: "text", required: false },
      { header: "utm_medium", kind: "text", required: false },
      {
        header: "dashboard_channel",
        kind: "text",
        required: true,
        enumValues: [
          "DTC (Shopify)",
          "Amazon FBA",
          "TikTok Shop",
          "Retail / Wholesale",
          "Distributor",
          "Unclassified",
        ],
      },
      {
        header: "sop_channel",
        kind: "text",
        required: false,
        enumValues: ["D2C / Website", "Retail", "Wholesale", "Not mapped"],
      },
      { header: "effective_from", kind: "date", required: true },
      { header: "effective_to", kind: "date", required: false },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: ["active", "inactive", "superseded"],
      },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Sales_Actuals: {
    name: "Sales_Actuals",
    tableName: "sales_actuals",
    businessKey: ["order_id"],
    columns: [
      { header: "order_id", kind: "text", required: true },
      { header: "customer_id", kind: "text", required: false },
      { header: "order_date", kind: "date", required: true },
      { header: "first_order_date", kind: "date", required: true },
      { header: "gross_product_sales_usd", kind: "usd", required: true },
      { header: "discounts_usd", kind: "usd", required: true },
      { header: "refunds_returns_usd", kind: "usd", required: true },
      { header: "cancellations_usd", kind: "usd", required: true },
      { header: "net_product_revenue_usd", kind: "usd", required: true },
      {
        header: "order_status",
        kind: "text",
        required: true,
        enumValues: ["paid", "confirmed", "partially_refunded", "refunded", "cancelled", "unpaid"],
      },
      { header: "acquisition_channel", kind: "text", required: true },
      { header: "currency", kind: "text", required: true, enumValues: ["USD"] },
      { header: "is_test", kind: "text", required: true, enumValues: ["yes", "no"] },
      { header: "data_as_of", kind: "date", required: true },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Inventory_Snapshots: {
    name: "Inventory_Snapshots",
    tableName: "inventory_snapshots",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "snapshot_at", kind: "timestamp", required: true },
      {
        header: "warehouse",
        kind: "text",
        required: true,
        enumValues: ["SNAPL 3PL", "YBYD", "139 North 10th Street", "In Transit", "Other"],
      },
      {
        header: "sku",
        kind: "text",
        required: true,
        enumValues: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
      },
      { header: "on_hand", kind: "integer", required: true },
      { header: "committed", kind: "integer", required: false },
      { header: "available", kind: "integer", required: false },
      { header: "damaged", kind: "integer", required: false },
      { header: "incoming", kind: "integer", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Inventory_Lots: {
    name: "Inventory_Lots",
    tableName: "inventory_lots",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      {
        header: "warehouse",
        kind: "text",
        required: true,
        enumValues: ["SNAPL 3PL", "YBYD", "139 North 10th Street", "In Transit", "Other"],
      },
      {
        header: "sku",
        kind: "text",
        required: true,
        enumValues: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
      },
      { header: "lot_number", kind: "text", required: true },
      { header: "production_date", kind: "date", required: false },
      { header: "received_date", kind: "date", required: false },
      { header: "best_by_date", kind: "date", required: true },
      { header: "quantity_received", kind: "integer", required: true },
      { header: "quantity_remaining", kind: "integer", required: true },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: [
          "in_transit",
          "received",
          "in_stock",
          "quarantine",
          "depleted",
          "expired",
          "written_off",
        ],
      },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Sales_Forecast: {
    name: "Sales_Forecast",
    tableName: "sales_forecast",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "forecast_version", kind: "text", required: true },
      { header: "week_start", kind: "date", required: true },
      {
        header: "sku",
        kind: "text",
        required: true,
        enumValues: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
      },
      {
        header: "channel",
        kind: "text",
        required: true,
        enumValues: [
          "DTC (Shopify)",
          "Amazon FBA",
          "TikTok Shop",
          "Retail / Wholesale",
          "Distributor",
          "Unclassified",
        ],
      },
      { header: "forecast_units", kind: "integer", required: true },
      { header: "forecast_revenue_usd", kind: "usd", required: true },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: ["draft", "submitted", "approved", "superseded"],
      },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Production_Orders: {
    name: "Production_Orders",
    tableName: "production_orders",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "po_number", kind: "text", required: true },
      {
        header: "sku",
        kind: "text",
        required: true,
        enumValues: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
      },
      { header: "units", kind: "integer", required: true },
      { header: "supplier", kind: "text", required: true },
      { header: "order_date", kind: "date", required: true },
      { header: "expected_date", kind: "date", required: false },
      { header: "received_date", kind: "date", required: false },
      { header: "received_units", kind: "integer", required: false },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: [
          "draft",
          "open",
          "confirmed",
          "in_production",
          "in_transit",
          "partially_received",
          "received",
          "cancelled",
        ],
      },
      { header: "unit_cost_usd", kind: "usd", required: true },
      { header: "freight_usd", kind: "usd", required: false },
      { header: "deposit_usd", kind: "usd", required: false },
      { header: "balance_usd", kind: "usd", required: false },
      { header: "payment_due_date", kind: "date", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Production_Schedule: {
    name: "Production_Schedule",
    tableName: "production_schedule",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "production_run", kind: "text", required: true },
      {
        header: "sku",
        kind: "text",
        required: true,
        enumValues: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
      },
      { header: "planned_start", kind: "date", required: true },
      { header: "planned_end", kind: "date", required: true },
      { header: "actual_start", kind: "date", required: false },
      { header: "actual_end", kind: "date", required: false },
      { header: "planned_units", kind: "integer", required: true },
      { header: "completed_units", kind: "integer", required: false },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: ["planned", "in_progress", "completed", "on_hold", "cancelled"],
      },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Additional_Depletions: {
    name: "Additional_Depletions",
    tableName: "additional_depletions",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "movement_date", kind: "date", required: true },
      {
        header: "warehouse",
        kind: "text",
        required: true,
        enumValues: ["SNAPL 3PL", "YBYD", "139 North 10th Street", "In Transit", "Other"],
      },
      {
        header: "sku",
        kind: "text",
        required: true,
        enumValues: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
      },
      { header: "quantity", kind: "integer", required: true },
      {
        header: "reason",
        kind: "text",
        required: true,
        enumValues: [
          "gifting",
          "sample",
          "influencer_seeding",
          "promotion",
          "event",
          "wastage",
          "damage",
          "quality_hold",
          "internal_use",
          "other",
        ],
      },
      { header: "recipient_or_project", kind: "text", required: false },
      { header: "reference", kind: "text", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  COGS_By_SKU: {
    name: "COGS_By_SKU",
    tableName: "cogs_by_sku",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      {
        header: "sku",
        kind: "text",
        required: true,
        enumValues: ["SKU-01", "SKU-02", "SKU-03", "SKU-04", "SKU-05"],
      },
      { header: "effective_from", kind: "date", required: true },
      { header: "effective_to", kind: "date", required: false },
      {
        header: "cost_basis",
        kind: "text",
        required: true,
        enumValues: ["standard", "actual", "landed", "quoted"],
      },
      { header: "production_cost_usd", kind: "usd", required: true },
      { header: "packaging_usd", kind: "usd", required: true },
      { header: "freight_usd", kind: "usd", required: true },
      { header: "fulfillment_usd", kind: "usd", required: false },
      { header: "total_unit_cost_usd", kind: "usd", required: true },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Finance_Actuals: {
    name: "Finance_Actuals",
    tableName: "finance_actuals",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "period", kind: "text", required: true },
      { header: "account_code", kind: "text", required: true },
      { header: "category", kind: "text", required: true },
      { header: "actual_amount_usd", kind: "usd", required: true },
      { header: "cash_or_accrual", kind: "text", required: true, enumValues: ["cash", "accrual"] },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: ["draft", "posted", "reconciled", "adjusted"],
      },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Cash_Position: {
    name: "Cash_Position",
    tableName: "cash_position",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "as_of_date", kind: "date", required: true },
      { header: "cash_balance_usd", kind: "usd", required: true },
      { header: "restricted_cash_usd", kind: "usd", required: false },
      { header: "expected_inflow_usd", kind: "usd", required: false },
      { header: "expected_outflow_usd", kind: "usd", required: false },
      { header: "due_date", kind: "date", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Marketing_Spend: {
    name: "Marketing_Spend",
    tableName: "marketing_spend",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "date", kind: "date", required: true },
      {
        header: "platform",
        kind: "text",
        required: true,
        enumValues: ["meta", "tiktok", "google", "amazon_ads", "pinterest", "klaviyo", "other"],
      },
      { header: "account", kind: "text", required: true },
      { header: "campaign_id", kind: "text", required: false },
      { header: "campaign_name", kind: "text", required: false },
      { header: "spend_usd", kind: "usd", required: true },
      { header: "impressions", kind: "integer", required: false },
      { header: "clicks", kind: "integer", required: false },
      { header: "conversions", kind: "integer", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Social_Metrics: {
    name: "Social_Metrics",
    tableName: "social_metrics",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "snapshot_date", kind: "date", required: true },
      {
        header: "platform",
        kind: "text",
        required: true,
        enumValues: [
          "instagram",
          "tiktok",
          "youtube",
          "linkedin",
          "x",
          "facebook",
          "pinterest",
          "other",
        ],
      },
      { header: "account", kind: "text", required: true },
      { header: "followers", kind: "integer", required: false },
      { header: "reach", kind: "integer", required: false },
      { header: "impressions", kind: "integer", required: false },
      { header: "engagements", kind: "integer", required: false },
      { header: "link_clicks", kind: "integer", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Affiliate_Ambassador_Perf: {
    name: "Affiliate_Ambassador_Perf",
    tableName: "affiliate_ambassador_perf",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "period", kind: "text", required: true },
      { header: "partner_id", kind: "text", required: true },
      { header: "partner_name", kind: "text", required: true },
      {
        header: "platform",
        kind: "text",
        required: false,
        enumValues: ["instagram", "tiktok", "youtube", "campus", "web", "email", "other"],
      },
      { header: "code_or_link", kind: "text", required: true },
      { header: "orders", kind: "integer", required: false },
      { header: "revenue_usd", kind: "usd", required: false },
      { header: "commission_usd", kind: "usd", required: false },
      { header: "posts", kind: "integer", required: false },
      { header: "reach", kind: "integer", required: false },
      { header: "clicks", kind: "integer", required: false },
      {
        header: "payout_status",
        kind: "text",
        required: false,
        enumValues: ["pending", "approved", "paid", "on_hold", "cancelled"],
      },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Growth_Pipeline: {
    name: "Growth_Pipeline",
    tableName: "growth_pipeline",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      {
        header: "pipeline_type",
        kind: "text",
        required: true,
        enumValues: ["retail", "collaboration", "partnership", "investor", "grant"],
      },
      { header: "opportunity", kind: "text", required: true },
      {
        header: "stage",
        kind: "text",
        required: true,
        enumValues: [
          "prospect",
          "contacted",
          "in_discussion",
          "proposal_sent",
          "negotiation",
          "won",
          "lost",
          "on_hold",
        ],
      },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: ["open", "won", "lost", "stalled"],
      },
      { header: "value_usd", kind: "usd", required: false },
      { header: "probability_manual", kind: "percent", required: false },
      { header: "created_date", kind: "date", required: true },
      { header: "last_activity_date", kind: "date", required: false },
      { header: "next_action", kind: "text", required: false },
      { header: "next_action_date", kind: "date", required: false },
      { header: "closed_date", kind: "date", required: false },
      { header: "actual_value_usd", kind: "usd", required: false },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
  Metric_Targets: {
    name: "Metric_Targets",
    tableName: "metric_targets",
    businessKey: ["record_id"],
    columns: [
      { header: "record_id", kind: "text", required: true },
      { header: "metric_key", kind: "text", required: true },
      { header: "period_start", kind: "date", required: true },
      { header: "period_end", kind: "date", required: true },
      { header: "target_value", kind: "decimal", required: true },
      {
        header: "unit",
        kind: "text",
        required: true,
        enumValues: ["usd", "units", "percent", "ratio", "count", "days"],
      },
      {
        header: "scope_type",
        kind: "text",
        required: true,
        enumValues: ["company", "channel", "sku", "location", "campaign"],
      },
      { header: "scope_value", kind: "text", required: false },
      {
        header: "status",
        kind: "text",
        required: true,
        enumValues: ["active", "inactive", "achieved", "missed"],
      },
      {
        header: "source_status",
        kind: "text",
        required: false,
        enumValues: ["production", "draft", "example", "invalid"],
      },
      { header: "data_as_of", kind: "date", required: false },
      { header: "created_at", kind: "timestamp", required: false },
      { header: "updated_at", kind: "timestamp", required: false },
      { header: "updated_by", kind: "text", required: false },
      { header: "source_reference", kind: "text", required: false },
      { header: "notes", kind: "text", required: false },
    ],
  },
};
